# Generated by Django 5.0.6 on 2024-07-11 13:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('brand_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_name', models.CharField(max_length=50)),
                ('car_image', models.ImageField(upload_to='car_app/media/car_images')),
                ('car_discription', models.TextField()),
                ('car_price', models.IntegerField()),
                ('car_quantity', models.IntegerField()),
                ('car_brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='brand_app.brand')),
            ],
        ),
    ]
